spring.application.name=secondhandmarket

server.port=${PORT:9000}


# Configuración de sesiones
spring.session.store-type=jdbc
spring.session.jdbc.initialize-schema=always

# Configuración de base de datos (en lugar de memoria RAM)
spring.datasource.url=${DATABASE_URL}
spring.datasource.username=${DB_USERNAME}
spring.datasource.password=${DB_PASSWORD}

# H2 Consola  http://localhost:9000/h2-console
#spring.h2.console.enabled=false
#spring.h2.console.path=/h2-console
#spring.h2.console.settings.web-allow-others=true
#spring.h2.console.settings.trace=false



spring.jpa.show-sql=true
spring.jpa.hibernate.ddl-auto=update
spring.jpa.properties.hibernate.id.new_generator_mappings=false

# Especificar dialecto para evitar fallo al detectar Dialect por JDBC
spring.jpa.database-platform=org.hibernate.dialect.PostgreSQLDialect
spring.jpa.properties.hibernate.dialect=org.hibernate.dialect.PostgreSQLDialect
